adding commands to process generic bibliography files

diff --git a/beamer-slides/basic-beamer-template/Makefile b/beamer-slides/basic-beamer-template/Makefile
--- a/beamer-slides/basic-beamer-template/Makefile
+++ b/beamer-slides/basic-beamer-template/Makefile
@@ -18,8 +18,18 @@ all: $(TARGET) #distribute clean
 
 $(TARGET): $(SOURCE) *tex 
 	@pdflatex $(SOURCE)
+	@pdflatex $(SOURCE)
+	###
 	#@bibtex $(NAME)
-	#@pdflatex $(SOURCE)
+	# check individual cases of bibliography files
+        [[ -f refs.bib && -f biblio.bib ]] && bibtex $(name) || echo "BIB file not found!"
+        # check for any BIB file
+        if [ -f *.bib ]; then\
+                for i in *bib; do \
+                        [[ -f $$i ]] && bibtex $(name);\
+                done;\
+        fi
+	###
 	@pdflatex $(SOURCE)
 
 clean:
