improved makefile, with comments, cleaning rules properly working, etc

diff --git a/beamer-slides/basic-beamer-template/Makefile b/beamer-slides/basic-beamer-template/Makefile
--- a/beamer-slides/basic-beamer-template/Makefile
+++ b/beamer-slides/basic-beamer-template/Makefile
@@ -1,15 +1,36 @@
+#####################################################################
+#
+#  Makefile for Latex compilation
+#
+#  Includes:
+#	- auto-detection of BIBliography files and auto compilation.
+#	- (soft) _clean_ rule to remove aux/intermediate files.
+#	- _hardclean_ rule to removealdo PDF + aux/intermediate files.
+#	- _distribute_ rule for copying/add-commit to repo.
+#
+#
+#  Author: Marcelo Ponce
+#
+#####################################################################
+
+
 NAME=lecture_wrapper
 TARGET=$(NAME).pdf
 SOURCE=$(NAME).tex
 # name of the PDF file that will be generated
 LECTURE="lecture_SLIDES.pdf"
 
+LATEX=`which pdflatex`
+BIBTEX=`which bibtex`
+
+RM=/bin/rm -f
+
 # location of repository where to commit changes in main lecture
 REPO="."
 
 # files to clean up
-JUNK=.aux .bbl .blg .brf .dvi .log .nav .out .ps .snm .vrb .tex.backup .tex.bak .toc Notes.bib .spl
-
+JUNK=.aux .bbl .blg .brf .dvi .log .nav .out .ps .snm .vrb .tex.backup .tex.bak .toc .spl 
+AUXfiles=Notes.bib textup.log
 
 
 .PHONY: clean
@@ -17,33 +38,46 @@ JUNK=.aux .bbl .blg .brf .dvi .log .nav .out .ps .snm .vrb .tex.backup .tex.bak 
 all: $(TARGET) #distribute clean 
 
 $(TARGET): $(SOURCE) *tex 
-	@pdflatex $(SOURCE)
-	@pdflatex $(SOURCE)
+	@$(LATEX) $(SOURCE)
+	@$(LATEX) $(SOURCE)
 	###
-	#@bibtex $(NAME)
+	# bibliography processing based on BIB file presence, instead of just using
+	# @bibtex $(NAME)
 	# check individual cases of bibliography files
-	[[ -f refs.bib && -f biblio.bib ]] && bibtex $(name) || echo "BIB file not found!"
+	[[ -f refs.bib && -f biblio.bib ]] && $(BIBTEX) $(NAME) || echo "BIB file not found!"
 	# check for any BIB file
-	if [ -f *.bib ]; then\
+	if [ -f *.bib ]; then \
 		for i in *bib; do \
-			[[ -f $$i ]] && bibtex $(name);\
-		done;\
+			if [[ -f $$i ]]; then	\
+				 $(BIBTEX) $(NAME); \
+			fi; \
+		done ; \
 	fi
 	###
-	@pdflatex $(SOURCE)
+	@$(LATEX) $(SOURCE)
 
 clean:
-	@for ext in $(JUNK); do \
-		rm -v $(NAME)$$ext; \
-		rm -v texput.log; \
-	done
+	@for ext in $(JUNK) ; do \
+		if [[ -f $(NAME)$$ext ]]; then	\
+			$(RM) $(NAME)$$ext ; \
+		fi;	\
+	done 
+	echo "the end"
 
-hardclean:
-	@for ext in $(JUNK) .pdf; do \
-		rm -v $(NAME)$$ext; \
-		rm -v texput.log; \
-	done
+	#for file in $(AUXfiles); do \
+	#	[[ -f $$file ]] && rm -v $$file; \
+	#done
+
+realclean: clean
+	[[ -f $(NAME).pdf ]] && rm -v $(NAME).pdf
+	#@for ext in $(JUNK) .pdf; do \
+	#	rm -v $(NAME)$$ext; \
+	#	rm -v texput.log; \
+	#done
 
 distribute:
 	cp -v $(TARGET) $(REPO)/$(LECTURE)
 	cd $(REPO) && git add $(LECTURE) && git commit -m "Adding $(LECTURE)" && git push 
+
+
+#####################################################################
